@startuml FiapRide
skinparam classAttributeIconSize 0

class Passageiro {
    - String nome
    - String cpf
    - double saldo
    + Passageiro(String nome, String cpf)
    + void adicionarSaldo(double valor)
    + void pagarViagem(double custo)
    + String getNome()
    + String getCpf()
    + double getSaldo()
    - void setNome(String nome)
    - void setCpf(String cpf)
    - void setSaldo(double valor)
}

class Viagem {
    - String destino
    - double valor
    + Viagem(String destino, Passageiro solicitante, Veiculo veiculoUtilizado)
    + void exibirResumo()
    + String getDestino()
    + Passageiro getSolicitante()
    + Veiculo getVeiculoUtilizado()
}

class Veiculo {
    - String placa
    - String modelo
    + Veiculo(String placa, String modelo)
    + void atualizarPlaca(String novaPlaca)
    + String getPlaca()
    + String getModelo()
    - void setPlaca(String novaPlaca)
}

class Celular {
    - String cor
    - int memoriaTotal
    - int memoria
    + Celular(String cor, int memoriaTotal, int memoriaInicial, Bateria bateria)
    + void instalarAplicativo(int tamanhoGb)
    + void esvaziarMemoria(int quantidadeLiberada)
    + String getCor()
    + int getMemoriaTotal()
    + int getMemoria()
    + Bateria getBateria()
    - void setCor(String cor)
    - void setMemoria(int valor)
}

class Bateria {
    - int capacidadeMah
    + Bateria(int capacidadeMah)
    + int getCapacidadeMah()
}

Viagem "0..*" --> "1" Passageiro : solicitante
Viagem "0..*" --> "1" Veiculo : veiculoUtilizado
Celular "1" --> "1" Bateria : bateria
@enduml
